In [32]:
import torch
import numpy as np

In [5]:
#check pytorch version
torch.__version__

'1.10.0+cu113'

In [9]:
x = torch.rand(3) #creating a random torch tensor
print(x)
print(type(x)) #In pytorch, everything is a tensor

tensor([0.1160, 0.2202, 0.0753])
<class 'torch.Tensor'>


In [8]:
torch.cuda.is_available() #check CUDA availabilty

True

In [17]:
x = torch.empty(2) #creating an empty tensor, values are not initialised yet
print(x)
print(type(x))

tensor([3.6013e-43, 0.0000e+00])
<class 'torch.Tensor'>


In [18]:
x = torch.empty(4) #empty tensor, values are not initialised yet
print(x)

tensor([0.0000, 1.8750, 0.0000, 0.0000])


In [19]:
x = torch.empty(2,3) #2D 
print(x)

tensor([[0.0000e+00, 6.8664e-44, 6.5991e-10],
        [3.2502e+21, 1.3435e-05, 1.7375e-04]])


In [13]:
x = torch.empty(2,3,3) #3D
print(x)

tensor([[[1.0653e-38, 1.0194e-38, 8.4490e-39],
         [1.0469e-38, 9.3674e-39, 9.9184e-39],
         [8.7245e-39, 9.2755e-39, 8.9082e-39]],

        [[9.9184e-39, 8.4490e-39, 9.6429e-39],
         [1.0653e-38, 1.0469e-38, 4.2246e-39],
         [1.0378e-38, 9.6429e-39, 9.2755e-39]]])


In [18]:
x = torch.rand(2) #random tensor
print(x)

tensor([0.0911, 0.6132])


In [19]:
x = torch.rand(2,3) #random tensor
print(x)

tensor([[0.9635, 0.2956, 0.5240],
        [0.2020, 0.3476, 0.6713]])


In [22]:
x = torch.zeros(2,2) #all zero tensor
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [24]:
x = torch.ones(2,3) #all one tensor, by default the data type is float
print(x)
print(x.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [28]:
x = torch.ones(2,3,dtype=torch.int) #setting the data type of the tensor elements
print(x)
print(x.dtype)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
torch.int32


In [26]:
x = torch.ones(2,3,dtype=torch.double) 
print(x)
print(x.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
torch.float64


In [27]:
x = torch.ones(2,3,dtype=torch.float) 
print(x)
print(x.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [29]:
x = torch.ones(2,3,dtype=torch.float) 
print(x)
print(x.dtype) # Data type of the tensor elements
print(x.size()) # Size of the tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.float32
torch.Size([2, 3])


In [30]:
y = [1,2,3,4,5.8]
x = torch.tensor(y)
print(x)

tensor([1.0000, 2.0000, 3.0000, 4.0000, 5.8000])


In [31]:
x = torch.rand(2,2)
y = torch.rand(2,2)

In [43]:
#tensor operations
z = x+y #simple addition, element wise addition
print(z)

z = torch.add(x,y) #does the same as above
print(z)

y.add_(x)#in place addition, every function with "_" will do an inplace operation and will modify the original one
print(y)

z=x-y
print(z)
z = torch.sub(x,y) #x minus y (x-y)
print(z)
y.sub_(x) #y minus x (y-x)
print(y)
x.sub_(y) #x minus y (x-y)
print(x)


tensor([[2.1849, 0.4369],
        [1.7800, 1.2907]])
tensor([[2.1849, 0.4369],
        [1.7800, 1.2907]])
tensor([[2.1849, 0.4369],
        [1.7800, 1.2907]])
tensor([[-3.8051, -0.8544],
        [-3.2372, -2.2460]])
tensor([[-3.8051, -0.8544],
        [-3.2372, -2.2460]])
tensor([[3.8051, 0.8544],
        [3.2372, 2.2460]])
tensor([[-5.4253, -1.2719],
        [-4.6945, -3.2014]])


In [48]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z = x*y #element wise multiplication
print(z)
z = torch.mul(x,y) #element wise multiplication
print(z)
y.mul_(x) #functions with underscore "_" are inplace operations
print(y)


tensor([[0.1750, 0.1422],
        [0.0339, 0.1172]])
tensor([[0.1750, 0.1422],
        [0.0339, 0.1172]])
tensor([[0.1750, 0.1422],
        [0.0339, 0.1172]])


In [49]:
x = torch.rand(2,2)
y = torch.rand(2,2)

z = x/y #element wise division
print(z)
z = torch.div(x,y)
print(z)
y.div_(x)
print(y)

tensor([[1.1872, 1.2088],
        [1.3003, 0.4593]])
tensor([[1.1872, 1.2088],
        [1.3003, 0.4593]])
tensor([[0.8423, 0.8273],
        [0.7690, 2.1773]])


In [27]:
#Tensor Slicing
x = torch.rand(5,3)
print(x)

tensor([[0.5966, 0.4813, 0.4252],
        [0.7147, 0.5158, 0.1239],
        [0.0890, 0.9355, 0.5944],
        [0.2341, 0.8854, 0.8409],
        [0.3437, 0.8908, 0.2324]])


tensor([0.5966, 0.7147, 0.0890, 0.2341, 0.3437])

In [55]:
print(x[:,0]) #all rows, first column
print(x[:,1]) #all rows, second column
print(x[0,:]) #first row, all columns

print(x[1,1]) #element at 1,1 as tensor , not as data, need to use item() to acess the data

tensor([0.8793, 0.5474, 0.9924, 0.6182, 0.1334])
tensor([0.8816, 0.9787, 0.1730, 0.6370, 0.5224])
tensor([0.8793, 0.8816, 0.8957])
tensor(0.9787)


In [58]:
print(x[1,1]) #element at 1,1, this gives tensor
print(x[1,1].item()) #this gives actual value and not tensor, this works only when there is a single element in the tensor

tensor(0.9787)
0.9787145256996155


In [63]:
#reshaping a tensor
x = torch.rand(4,4)
print(x)
y = x.view(16) #total number of elements must match
print(y)
y = x.view(2,8)
print(y)
y = x.view(-1,8) #automatically detects the argument at "-1", if we cannot calculate the total number of elements
print(y)
y = x.view(2,-1)
print(y)

tensor([[0.5598, 0.5358, 0.0634, 0.5418],
        [0.6733, 0.2564, 0.2451, 0.5409],
        [0.4438, 0.0231, 0.0020, 0.0319],
        [0.1917, 0.3494, 0.6010, 0.7252]])
tensor([0.5598, 0.5358, 0.0634, 0.5418, 0.6733, 0.2564, 0.2451, 0.5409, 0.4438,
        0.0231, 0.0020, 0.0319, 0.1917, 0.3494, 0.6010, 0.7252])
tensor([[0.5598, 0.5358, 0.0634, 0.5418, 0.6733, 0.2564, 0.2451, 0.5409],
        [0.4438, 0.0231, 0.0020, 0.0319, 0.1917, 0.3494, 0.6010, 0.7252]])
tensor([[0.5598, 0.5358, 0.0634, 0.5418, 0.6733, 0.2564, 0.2451, 0.5409],
        [0.4438, 0.0231, 0.0020, 0.0319, 0.1917, 0.3494, 0.6010, 0.7252]])
tensor([[0.5598, 0.5358, 0.0634, 0.5418, 0.6733, 0.2564, 0.2451, 0.5409],
        [0.4438, 0.0231, 0.0020, 0.0319, 0.1917, 0.3494, 0.6010, 0.7252]])


In [72]:
#numpy to tensor and vice versa
import numpy as np

a = torch.ones(5)
print(a)

b = a.numpy() #tensor to a numpy array
print(b)
print("type of a",type(a))
print("type of b",type(b))

### if the tensor is on cpu and not gpu, both objects will share same memory location, changing one will change another
a.add_(1)
print(a)
print(b)


a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

### if the tensor is on cpu and not gpu, both objects will share same memory location, changing one will change another
a +=1
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
type of a <class 'torch.Tensor'>
type of b <class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [35]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    #all of the following variables are on CPU and not on GPU, both objects (torch tensor and numpy array) share same memory location
    a = np.ones(5)
    k = torch.from_numpy(a)
    c = torch.ones(5)
    f = c.numpy()

#Changing one object will result in changing both objects, as they share the same memory location
a+=1
print(a)
print(k)
f+=2
print(c)
print(f)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [37]:
torch.device("cuda") #accessing torch CUDA / GPU device

device(type='cuda')

In [38]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    a = np.ones(5)
    k = torch.from_numpy(a)
    c = torch.ones(5,device=device) # Variable created on GPU
    f = c.numpy() #Converting CUDA tensor to numpy directly, will result in an error

a+=1
print(a)
print(k)
f+=1
print(c)
print(f)

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [40]:
if torch.cuda.is_available():
    device = torch.device("cuda")

    a = np.ones(5) #numpy array
    k = torch.from_numpy(a) #converting numpy array to torch tensot

    c = torch.ones(5,device=device) #now the tensor is created on the GPU
    cc = c.cpu() #we need to copy the tensor from gpu to cpu memory first, numpy can only handle cpu tensors
    cc = c.to("cpu") #does the same as above line
    f = cc.numpy()

    x = torch.ones(5)
    y = x.to(device) #move to gpu

a+=1
print(a)
print(k) #both share same memory location, hence changing one would result in changing both

print("modifying CPU array")
f+=1 #cc,f share same memory location. changing one would result in chaning both, but doesnot effect GPU variable c
print(c) #GPU tensor
print(cc) #CPU tensor
print(f) # CPU array

print("modifying CPU tensor")
cc+=1 #cc,f share same memory location. changing one would result in chaning both, but doesnot effect GPU variable c
print(c) #GPU tensor
print(cc) #CPU tensor
print(f) # CPU array

print("modifying GPU tensor")
c.add_(5) #changing C does not effect CC & f
print(c)
print(cc)
print(f)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
modifying CPU array
tensor([1., 1., 1., 1., 1.], device='cuda:0')
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
modifying CPU tensor
tensor([1., 1., 1., 1., 1.], device='cuda:0')
tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]
modifying GPU tensor
tensor([6., 6., 6., 6., 6.], device='cuda:0')
tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [41]:
x = torch.ones(5,) 
print(x)
y = torch.ones(5,requires_grad=True) #this means that pytorch will need to calculate gradient for this tensor in later steps
#for variables we need to optimise, we need gradients, hence we need to specify reuires_grad
print(y)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.], requires_grad=True)
