In [1]:
import torch 
import torch.nn as nn
import numpy as np

In [16]:
def softmax(x):
    return np.exp(x)/np.exp(x).sum(axis=0)

In [18]:
x = np.array([1,2,3,4])
softmax_out = softmax(x)
print("x:",x)
print("softmax output:",softmax_out)
print("sum of softmax_out:",softmax_out.sum())

x: [1 2 3 4]
softmax output: [0.0320586  0.08714432 0.23688282 0.64391426]
sum of softmax_out: 1.0


In [21]:
#implementing the same in pytorch

x = torch.tensor([1,2,3,4],dtype=torch.float32)
out = torch.softmax(x,dim=0)
print("x:",x)
print("softmax output:",out)
print("sum of softmax_out:",out.sum())

x: tensor([1., 2., 3., 4.])
softmax output: tensor([0.0321, 0.0871, 0.2369, 0.6439])
sum of softmax_out: tensor(1.)


In [26]:
y_actual = np.array([1,0,0])
y_pred1 = np.array([0.7,0.2,0.1]) #good prediction
y_pred2 = np.array([0.1,0.3,0.6]) #bad prediction

In [27]:
def crossEntropy(actual,predicted):
    loss = -1*np.sum(actual*np.log(predicted))
    return loss/predicted.shape[0]


In [28]:
crossEntropy(y_actual,y_pred1)

0.11889164797957748

In [29]:
crossEntropy(y_actual,y_pred2) #how and why exactly cross entropy works

0.7675283643313485

In [30]:
loss_func = nn.CrossEntropyLoss() #when using cross entropy loss, we should not implement softmax function in last layer, CrossEntropyLoss automatically implements softmax
#also, ylabels (actual) should not be one hot encoded
#y_preds are raw scores (not softmax outputs)

In [36]:
y_actual = torch.tensor([0]) 
ypred1 = torch.tensor([[2.0, 1.0, 0.1]]) # n_samples * n_classes (here 1x3)
ypred2 = torch.tensor([[0.5, 2.0, 0.2]]) # n_samples * n_classes (here 1x3)

In [37]:
loss_func(ypred1,y_actual)

tensor(0.4170)

In [38]:
loss_func(ypred2,y_actual)

tensor(1.8282)

In [39]:
_,pred1 = torch.max(ypred1,1)
_,pred2 = torch.max(ypred2,1)

In [40]:
pred1

tensor([0])

In [41]:
pred2

tensor([1])

In [47]:
#3 samples , 3 possible classes
# y pred will be of size, 3x3

y_actual = torch.tensor([2,0,1])
y_pred1 = torch.tensor([[0.1,0.2,0.9],[2,0.1,0.5],[0.6,3,0.1]]) # n_samples x n_classes

In [49]:
loss_func(y_pred1,y_actual)

tensor(0.3729)

In [50]:
_,pred1 = torch.max(y_pred1,1)
pred1

tensor([2, 0, 1])