In [1]:
import torch
import torchvision #what does this do?
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn
import numpy as np
import math

In [2]:
# Loading the dataset - batches
# Design the model - inp features, out features, forward pass
# Loss & Optimiser
# training Loop - Forwards, Backward, weight updation (batch loops inside epoch loop)

In [ ]:
'''
Epoch - 1 forward and backward pass of all the training samples
batch size - number of samples in on forward and backward pass
number of iterations - numbr of passes, each pass using batch size number of samples
'''

In [12]:
# Dataset and Dataloader
class WineDataset(Dataset):
    def __init__(self):
        # data loading
        xy = np.loadtxt("9.Wine.csv",delimiter=',',dtype=np.float32,skiprows=1) #skipping the header
        self.x = torch.from_numpy(xy[:, 1:].astype(np.float32)) #first column is thr wine class category
        self.y = torch.from_numpy(xy[:, [0]].astype(np.float32))  #makes it n_samples x 1, column vector

        self.n_samples, self.n_features = xy.shape 

    def __getitem__(self,index):
        #dataset[0] - helps in indexing data samples
        return self.x[index], self.y[index]
    def __len__(self):
        #len(dataset)
        return self.n_samples

In [20]:
dataset = WineDataset()

In [25]:
#using indexing
first_dat = dataset[0]
features,labels = first_dat
print("features :")
print(features)
print("labels :")
print(labels)

features :
tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03])
labels :
tensor([1.])


In [41]:
#usind the data loader

dataloader = DataLoader(dataset=dataset, batch_size=4,shuffle=True,num_workers=0) #what is num workers? multiple subprocesses
#for now use num_worker=0, check how to use num_workers>0? and uppdate the notebook for that

In [46]:
dataiter = iter(dataloader)
data = dataiter.next()

data = dataiter.next()
features,labels = data
print("features :")
print(features)
print("labels :")
print(labels)

features :
tensor([[1.3400e+01, 4.6000e+00, 2.8600e+00, 2.5000e+01, 1.1200e+02, 1.9800e+00,
         9.6000e-01, 2.7000e-01, 1.1100e+00, 8.5000e+00, 6.7000e-01, 1.9200e+00,
         6.3000e+02],
        [1.3580e+01, 1.6600e+00, 2.3600e+00, 1.9100e+01, 1.0600e+02, 2.8600e+00,
         3.1900e+00, 2.2000e-01, 1.9500e+00, 6.9000e+00, 1.0900e+00, 2.8800e+00,
         1.5150e+03],
        [1.2200e+01, 3.0300e+00, 2.3200e+00, 1.9000e+01, 9.6000e+01, 1.2500e+00,
         4.9000e-01, 4.0000e-01, 7.3000e-01, 5.5000e+00, 6.6000e-01, 1.8300e+00,
         5.1000e+02],
        [1.3560e+01, 1.7100e+00, 2.3100e+00, 1.6200e+01, 1.1700e+02, 3.1500e+00,
         3.2900e+00, 3.4000e-01, 2.3400e+00, 6.1300e+00, 9.5000e-01, 3.3800e+00,
         7.9500e+02]])
labels :
tensor([[3.],
        [1.],
        [3.],
        [1.]])


In [51]:
features.shape
#4 samples, as the batch size is 4 and 14 features for each sample

torch.Size([4, 13])

In [52]:
labels.shape
#4 samples, as the batch size is 4 and 1 label for each sample

torch.Size([4, 1])

In [61]:
# training loop example
epochs = 2
learning_rate = 0.1
batch_size= 4
total_samples = len(dataset)
n_iterations = math.ceil(total_samples/batch_size)

print(total_samples,n_iterations)

178 45


In [62]:
for epoch in range(epochs):
    for i,(inputs,labels) in enumerate(dataloader):
        #loads one batch at a time
        # forward , backward, weight updation
        if ((i+1)%5==0) :
            print(f'epoch {epoch+1}/{epochs}, step {i+1}/{n_iterations}, inputs {inputs.shape}')


#tensor is 4x13, 4 samples in each batch with 13 features
# 45 steps (45 batches) in each epoch

epoch 1/2, step 5/45, inputs torch.Size([4, 13])
epoch 1/2, step 10/45, inputs torch.Size([4, 13])
epoch 1/2, step 15/45, inputs torch.Size([4, 13])
epoch 1/2, step 20/45, inputs torch.Size([4, 13])
epoch 1/2, step 25/45, inputs torch.Size([4, 13])
epoch 1/2, step 30/45, inputs torch.Size([4, 13])
epoch 1/2, step 35/45, inputs torch.Size([4, 13])
epoch 1/2, step 40/45, inputs torch.Size([4, 13])
epoch 1/2, step 45/45, inputs torch.Size([2, 13])
epoch 2/2, step 5/45, inputs torch.Size([4, 13])
epoch 2/2, step 10/45, inputs torch.Size([4, 13])
epoch 2/2, step 15/45, inputs torch.Size([4, 13])
epoch 2/2, step 20/45, inputs torch.Size([4, 13])
epoch 2/2, step 25/45, inputs torch.Size([4, 13])
epoch 2/2, step 30/45, inputs torch.Size([4, 13])
epoch 2/2, step 35/45, inputs torch.Size([4, 13])
epoch 2/2, step 40/45, inputs torch.Size([4, 13])
epoch 2/2, step 45/45, inputs torch.Size([2, 13])


In [ ]:
torchvision.datasets.MNIST()
#fashion MNIST, CIFAR, coco - read more about all the datasets